/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BidetsBidetIdRouteImport } from './routes/bidets/$bidetId'
import { Route as appSubmitRouteImport } from './routes/(app)/submit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BidetsBidetIdRoute = BidetsBidetIdRouteImport.update({
  id: '/bidets/$bidetId',
  path: '/bidets/$bidetId',
  getParentRoute: () => rootRouteImport,
} as any)
const appSubmitRoute = appSubmitRouteImport.update({
  id: '/(app)/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/submit': typeof appSubmitRoute
  '/bidets/$bidetId': typeof BidetsBidetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/submit': typeof appSubmitRoute
  '/bidets/$bidetId': typeof BidetsBidetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/(app)/submit': typeof appSubmitRoute
  '/bidets/$bidetId': typeof BidetsBidetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/profile'
    | '/register'
    | '/upload'
    | '/submit'
    | '/bidets/$bidetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/profile'
    | '/register'
    | '/upload'
    | '/submit'
    | '/bidets/$bidetId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/profile'
    | '/register'
    | '/upload'
    | '/(app)/submit'
    | '/bidets/$bidetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  appSubmitRoute: typeof appSubmitRoute
  BidetsBidetIdRoute: typeof BidetsBidetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bidets/$bidetId': {
      id: '/bidets/$bidetId'
      path: '/bidets/$bidetId'
      fullPath: '/bidets/$bidetId'
      preLoaderRoute: typeof BidetsBidetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/submit': {
      id: '/(app)/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof appSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  appSubmitRoute: appSubmitRoute,
  BidetsBidetIdRoute: BidetsBidetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
